version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./database.db
      - LLM_URL=http://llm:11434
      - DEBUG=true
    volumes:
      - ./app:/app
      - ./database.db:/app/database.db
    depends_on:
      - llm
    restart: unless-stopped

  llm:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama pull llama3:8b && ollama serve"
    restart: unless-stopped

volumes:
  ollama_data:
