services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      <<: *common-variables
    volumes:
      - ./app:/app
      - ./database.db:/app/database.db
    depends_on:
      - llm
    restart: unless-stopped

  llm:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama pull llama3:8b && ollama serve"
    restart: unless-stopped

volumes:
  ollama_data:
