version: '3.8'

services:
  llm-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - LOG_LEVEL=INFO
      - DEBUG=false
    depends_on:
      - ollama
    networks:
      - llm-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - llm-network
    restart: unless-stopped
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:

networks:
  llm-network:
    driver: bridge
